### ISSUE TITLE
Foodsearch layout

### ISSUE THREAD

**Issue by mhenning3** [TheHotMessExpress/recipe-finder#34]
As a user I want to navigate the page in a clear and concise way

-fix hidden  button on pantry

-Get rid of inner box on food search

-general margin and styling tweaks (make register page have box

-change max daily to max daily percentage

**Comment by sjiang1** [comment]
Please "have a reference to one or more beta testing reports that show why the change is important"

**Comment by mhenning3** [comment]
Stemmed from issues found in my beta test. reasons for each:

-fix hidden button on pantry (user could not see it and became confused how pantry worked)

-Get rid of inner box on food search (Scroll conflicted with settings on outer box)

-general margin and styling tweaks (titles hard to read)

-change max daily to max daily percentage (user stated it was unclear what the measurement unit was)
