### ISSUE TITLE
New "Home" page and changing the navigation bar to reflect these changes

### ISSUE THREAD

**Issue by jjjjess** [TheHotMessExpress/recipe-finder#38]
As a user, I think that the first page loaded should be the "FoodSearch" page, as it is arguably the most important page on the application. Then, I think the navigation bar should reflect these changes. Currently, the "Home" button is more of an "About" page. 

Reference from Andrew's beta testing report:
They suggested that the current home page become an “about page”.

Acceptance Criteria: 
 - When launched, the first page should be the current "FoodSearch" page
 - The navigation bar labels should be changed to better apply to the pages
        - "Home" changed to "About"
        - "Recipe" changed to  "Recently Viewed Recipe"

**Comment by amoots-emich** [comment]
Closed with PR #40
